spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://terning22.c144kqey41qd.ap-northeast-2.rds.amazonaws.com/terning22
    username: terning22
    password: terning1!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
